# Azure Web App Module

resource "azurerm_linux_web_app" "main" {
  name                = var.app_name
  resource_group_name = var.resource_group_name
  location            = var.location
  service_plan_id     = var.service_plan_id

  site_config {
    always_on = var.always_on

    application_stack {
      docker_image_name        = var.docker_image
      docker_registry_url      = "https://${var.acr_login_server}"
      docker_registry_username = var.acr_username
      docker_registry_password = var.acr_password
    }

    health_check_path = var.health_check_path

    # CORS configuration
    dynamic "cors" {
      for_each = length(var.cors_allowed_origins) > 0 ? [1] : []
      content {
        allowed_origins     = var.cors_allowed_origins
        support_credentials = var.cors_support_credentials
      }
    }
  }

  # Application Logging Configuration
  logs {
    # Enable application logs to file system
    application_logs {
      file_system_level = "Information"
    }

    # Enable HTTP logs to file system
    http_logs {
      file_system {
        retention_in_mb   = 35
        retention_in_days = 7
      }
    }

    # Enable detailed error messages
    detailed_error_messages = true

    # Enable failed request tracing
    failed_request_tracing = true
  }

  app_settings = merge(
    var.app_settings,
    var.enable_authentication ? {
      MICROSOFT_PROVIDER_AUTHENTICATION_SECRET = var.client_secret
    } : {}
  )

  identity {
    type = "SystemAssigned"
  }

  # Easy Auth configuration on main app
  dynamic "auth_settings" {
    for_each = var.enable_authentication ? [1] : []
    content {
      enabled = true
      # auth_settings v1: "AllowAnonymous" (401) or "RedirectToLoginPage" (302)
      unauthenticated_client_action = var.unauthenticated_action == "RedirectToLoginPage" ? "RedirectToLoginPage" : "AllowAnonymous"
      default_provider              = var.unauthenticated_action == "RedirectToLoginPage" ? "AzureActiveDirectory" : null
      token_store_enabled           = true

      active_directory {
        client_id     = var.client_id
        client_secret = var.client_secret
        allowed_audiences = length(var.allowed_audiences) > 0 ? var.allowed_audiences : [
          "api://${var.client_id}"
        ]
      }
    }
  }

  https_only = true

  tags = var.tags
}

# VNet Integration
resource "azurerm_app_service_virtual_network_swift_connection" "main" {
  count = var.enable_vnet_integration ? 1 : 0

  app_service_id = azurerm_linux_web_app.main.id
  subnet_id      = var.vnet_integration_subnet_id
}

# Diagnostic Settings for Production Slot
resource "azurerm_monitor_diagnostic_setting" "web_app" {
  name                       = "${var.app_name}-diagnostics"
  target_resource_id         = azurerm_linux_web_app.main.id
  log_analytics_workspace_id = var.log_analytics_workspace_id

  # HTTP Logs - Incoming HTTP requests on App Service
  enabled_log {
    category = "AppServiceHTTPLogs"
  }

  # Console Logs - Logs generated from application or container
  enabled_log {
    category = "AppServiceConsoleLogs"
  }

  # Application Logs - Logs generated by the application code
  enabled_log {
    category = "AppServiceAppLogs"
  }

  # Platform Logs - Logs generated through AppService platform
  enabled_log {
    category = "AppServicePlatformLogs"
  }

  # Audit Logs - Logs for accessing app content
  enabled_log {
    category = "AppServiceAuditLogs"
  }

  # IP Security Audit Logs - IP restriction audit logs
  enabled_log {
    category = "AppServiceIPSecAuditLogs"
  }

  # Metrics
  metric {
    category = "AllMetrics"
    enabled  = true
  }

  # Easy Auth Logs - Authentication and authorization events
  enabled_log {
    category = "AppServiceAuthenticationLogs"
  }
}

# ============================================================================
# STAGING SLOT (for Blue-Green Deployments)
# ============================================================================

resource "azurerm_linux_web_app_slot" "staging" {
  count = var.supports_deployment_slots ? 1 : 0

  name           = "staging"
  app_service_id = azurerm_linux_web_app.main.id

  site_config {
    always_on = var.always_on

    application_stack {
      docker_image_name        = var.docker_image
      docker_registry_url      = "https://${var.acr_login_server}"
      docker_registry_username = var.acr_username
      docker_registry_password = var.acr_password
    }

    health_check_path = var.health_check_path

    # CORS configuration
    dynamic "cors" {
      for_each = length(var.cors_allowed_origins) > 0 ? [1] : []
      content {
        allowed_origins     = var.cors_allowed_origins
        support_credentials = var.cors_support_credentials
      }
    }
  }

  # Application Logging Configuration
  logs {
    # Enable application logs to file system
    application_logs {
      file_system_level = "Information"
    }

    # Enable HTTP logs to file system
    http_logs {
      file_system {
        retention_in_mb   = 35
        retention_in_days = 7
      }
    }

    # Enable detailed error messages
    detailed_error_messages = true

    # Enable failed request tracing
    failed_request_tracing = true
  }

  app_settings = merge(
    var.app_settings,
    var.enable_authentication ? {
      MICROSOFT_PROVIDER_AUTHENTICATION_SECRET = var.client_secret
    } : {}
  )

  identity {
    type = "SystemAssigned"
  }

  # Easy Auth configuration on staging slot
  dynamic "auth_settings" {
    for_each = var.enable_authentication ? [1] : []
    content {
      enabled = true
      # auth_settings v1: "AllowAnonymous" (401) or "RedirectToLoginPage" (302)
      unauthenticated_client_action = var.unauthenticated_action == "RedirectToLoginPage" ? "RedirectToLoginPage" : "AllowAnonymous"
      default_provider              = var.unauthenticated_action == "RedirectToLoginPage" ? "AzureActiveDirectory" : null
      token_store_enabled           = true
      issuer                        = "https://sts.windows.net/${var.tenant_id}/"

      active_directory {
        client_id     = var.client_id
        client_secret = var.client_secret
        allowed_audiences = length(var.allowed_audiences) > 0 ? var.allowed_audiences : [
          "api://${var.client_id}"
        ]
      }
    }
  }

  https_only = true

  tags = var.tags
}

# NOTE: Deployment slots inherit VNet integration from the main app
# No separate VNet integration resource needed for staging slot

# Diagnostic Settings for Staging Slot
resource "azurerm_monitor_diagnostic_setting" "staging_slot" {
  count = var.supports_deployment_slots ? 1 : 0

  name                       = "${var.app_name}-staging-diagnostics"
  target_resource_id         = azurerm_linux_web_app_slot.staging[0].id
  log_analytics_workspace_id = var.log_analytics_workspace_id

  # HTTP Logs - Incoming HTTP requests on App Service
  enabled_log {
    category = "AppServiceHTTPLogs"
  }

  # Console Logs - Logs generated from application or container
  enabled_log {
    category = "AppServiceConsoleLogs"
  }

  # Application Logs - Logs generated by the application code
  enabled_log {
    category = "AppServiceAppLogs"
  }

  # Platform Logs - Logs generated through AppService platform
  enabled_log {
    category = "AppServicePlatformLogs"
  }

  # Audit Logs - Logs for accessing app content
  enabled_log {
    category = "AppServiceAuditLogs"
  }

  # IP Security Audit Logs - IP restriction audit logs
  enabled_log {
    category = "AppServiceIPSecAuditLogs"
  }

  # Metrics
  metric {
    category = "AllMetrics"
    enabled  = true
  }
}
